
name: documentation

on:
  workflow_dispatch:
  # push:
  #   branches:
  #   - main

env:
  PYTHON_VERSION: '3.11'

permissions:
  contents: write

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull submodules
        run: |
          git submodule update --init

      - name: Install GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Install cmake
        uses: lukka/get-cmake@latest

      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install Sphinx and breathe (workaround)
        run: |
          sudo apt-get install -y python3-sphinx python3-breathe

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt

      - name: Compile
        run: |
          mkdir -p build
          cd build
          cmake .. -DBUILD_DOCUMENTATION=ON
          cmake --build .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact-docs
          path: build/docs/sphinx

  deploy:
    runs-on: ubuntu-latest
    needs: [ extract ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact-docs
          path: build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          destination_dir: ./
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

  cleanup:
    runs-on: ubuntu-latest
    if: always()
    needs: deploy
    steps:
      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          failOnError: false
          name: |
            artifact-*
